export const trendingAll = {
  page: 1,
  results: [
    {
      backdrop_path: '/fYnEbgoNCxW9kL0IgOgtJb9JTBU.jpg',
      id: 426063,
      title: 'Nosferatu',
      original_title: 'Nosferatu',
      overview:
        'A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.',
      poster_path: '/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [27],
      popularity: 1359.239,
      release_date: '2024-12-25',
      video: false,
      vote_average: 6.658,
      vote_count: 1322,
    },
    {
      backdrop_path: '/gklrevVndG98GHGDwfm8y8kxESo.jpg',
      id: 129552,
      name: 'The Night Agent',
      original_name: 'The Night Agent',
      overview:
        'Brought together by a midnight phone call, an FBI agent and a cybersecurity expert must unravel an ever-growing web of political conspiracies.',
      poster_path: '/4c5yUNcaff4W4aPrkXE6zr7papX.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 9648, 10759],
      popularity: 336.344,
      first_air_date: '2023-03-23',
      vote_average: 7.8,
      vote_count: 761,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/zGLQmrmIB56kMZPnzqReIOBay1B.jpg',
      id: 507241,
      title: "The Killer's Game",
      original_title: "The Killer's Game",
      overview:
        "When top hitman Joe Flood is diagnosed with a terminal illness, he decides to take matters into his own hands – by taking a hit out on himself. But when the very hitmen he hired also target his ex-girlfriend, he must fend off an army of assassin colleagues and win back the love of his life before it's too late.",
      poster_path: '/4bKlTeOUr5AKrLky8mwWvlQqyVd.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 35, 80],
      popularity: 129.34,
      release_date: '2024-09-12',
      video: false,
      vote_average: 6.7,
      vote_count: 195,
    },
    {
      backdrop_path: '/b85bJfrTOSJ7M5Ox0yp4lxIxdG1.jpg',
      id: 939243,
      title: 'Sonic the Hedgehog 3',
      original_title: 'Sonic the Hedgehog 3',
      overview:
        'Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.',
      poster_path: '/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 878, 35, 10751],
      popularity: 6277.745,
      release_date: '2024-12-19',
      video: false,
      vote_average: 7.768,
      vote_count: 875,
    },
    {
      backdrop_path: '/uKb22E0nlzr914bA9KyA5CVCOlV.jpg',
      id: 402431,
      title: 'Wicked',
      original_title: 'Wicked',
      overview:
        "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
      poster_path: '/2E1x1qcHqGZcYuYi4PzVZjzg8IV.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 10749, 14],
      popularity: 1055.946,
      release_date: '2024-11-20',
      video: false,
      vote_average: 7,
      vote_count: 1435,
    },
    {
      backdrop_path: '/4cp40IyTpFfsT2IKpl0YlUkMBIR.jpg',
      id: 1064213,
      title: 'Anora',
      original_title: 'Anora',
      overview:
        'A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled.',
      poster_path: '/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [10749, 35, 18],
      popularity: 495.268,
      release_date: '2024-10-14',
      video: false,
      vote_average: 7.001,
      vote_count: 786,
    },
    {
      backdrop_path: '/hmZnqijPaaACjenDkrbWcCmcADI.jpg',
      id: 549509,
      title: 'The Brutalist',
      original_title: 'The Brutalist',
      overview:
        'Escaping post-war Europe, visionary architect László Tóth arrives in America to rebuild his life, his work, and his marriage to his wife Erzsébet after being forced apart during wartime by shifting borders and regimes. On his own in a strange new country, László settles in Pennsylvania, where the wealthy and prominent industrialist Harrison Lee Van Buren recognizes his talent for building. But power and legacy come at a heavy cost.',
      poster_path: '/vP7Yd6couiAaw9jgMd5cjMRj3hQ.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [18],
      popularity: 170.958,
      release_date: '2024-12-20',
      video: false,
      vote_average: 5.25,
      vote_count: 46,
    },
    {
      backdrop_path: '/u2eA9pqi1q3DvevT7RuDuJHxxBT.jpg',
      id: 974950,
      title: 'Emilia Pérez',
      original_title: 'Emilia Pérez',
      overview:
        'Rita, an underrated lawyer working for a large law firm more interested in getting criminals out of jail than bringing them to justice, is hired by the leader of a criminal organization.',
      poster_path: '/7seqaCaaXDNUHOx4DqwpoOH8pPa.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'fr',
      genre_ids: [18, 53],
      popularity: 229.26,
      release_date: '2024-08-21',
      video: false,
      vote_average: 7.7,
      vote_count: 866,
    },
    {
      backdrop_path: '/bFPqSvR2EmWQ9AlzWkC801XpoAZ.jpg',
      id: 933260,
      title: 'The Substance',
      original_title: 'The Substance',
      overview:
        'A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.',
      poster_path: '/lqoMzCcZYEFK729d6qzt349fB4o.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [27, 878],
      popularity: 850.494,
      release_date: '2024-09-07',
      video: false,
      vote_average: 7.1,
      vote_count: 3373,
    },
    {
      backdrop_path: '/66nlC5LDZmDUWONGkUZT2BrOszG.jpg',
      id: 974576,
      title: 'Conclave',
      original_title: 'Conclave',
      overview:
        'After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.',
      poster_path: '/m5x8D0bZ3eKqIVWZ5y7TnZ2oTVg.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [18],
      popularity: 269.122,
      release_date: '2024-10-25',
      video: false,
      vote_average: 7.132,
      vote_count: 916,
    },
    {
      backdrop_path: '/j9uruwRe9qM8RnP758dF7ISB8Bj.jpg',
      id: 1000837,
      title: "I'm Still Here",
      original_title: 'Ainda Estou Aqui',
      overview:
        'In the early 1970s, the military dictatorship in Brazil reaches its height. The Paiva family - Rubens, Eunice, and their five children - live in a beachside house in Rio, open to all their friends. One day, Rubens is taken for questioning and does not return.',
      poster_path: '/qNLMPY3KLrYgTX2QZ5iEwwOqyRz.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'pt',
      genre_ids: [18, 36],
      popularity: 77.493,
      release_date: '2024-09-19',
      video: false,
      vote_average: 8.5,
      vote_count: 158,
    },
    {
      backdrop_path: '/4WHRiFgbsAuSJ79fyr8pTXkj4G2.jpg',
      id: 661539,
      title: 'A Complete Unknown',
      original_title: 'A Complete Unknown',
      overview:
        'New York, early 1960s. Against the backdrop of a vibrant music scene and tumultuous cultural upheaval, an enigmatic 19-year-old from Minnesota arrives in the West Village with his guitar and revolutionary talent, destined to change the course of American music.',
      poster_path: '/662Mk69uIJvjA1zb5PYP4geje9H.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 10402, 36],
      popularity: 119.27,
      release_date: '2024-12-18',
      video: false,
      vote_average: 7.5,
      vote_count: 68,
    },
    {
      backdrop_path: '/ehEvtUGaFPQ3EBZJCLJIv8a40vR.jpg',
      id: 246381,
      name: 'Prime Target',
      original_name: 'Prime Target',
      overview:
        'A brilliant math student is on the verge of a major breakthrough when a shadowy enemy tries to stop him. Fighting for answers—and his life—he teams up with a government agent to unravel a high-stakes conspiracy.',
      poster_path: '/bGYCimDXRL7cE3uETLZzMCFOdJo.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 80],
      popularity: 157.353,
      first_air_date: '2025-01-22',
      vote_average: 7.5,
      vote_count: 14,
      origin_country: ['GB'],
    },
    {
      backdrop_path: '/xZm5YUNY3PlYD1Q4k7X8zd2V4AK.jpg',
      id: 993710,
      title: 'Back in Action',
      original_title: 'Back in Action',
      overview:
        'Fifteen years after vanishing from the CIA to start a family, elite spies Matt and Emily jump back into the world of espionage when their cover is blown.',
      poster_path: '/3L3l6LsiLGHkTG4RFB2aBA6BttB.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 35],
      popularity: 2277.176,
      release_date: '2025-01-15',
      video: false,
      vote_average: 6.7,
      vote_count: 419,
    },
    {
      backdrop_path: '/ixgFmf1X59PUZam2qbAfskx2gQr.jpg',
      id: 95396,
      name: 'Severance',
      original_name: 'Severance',
      overview:
        'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.',
      poster_path: '/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 9648, 10765],
      popularity: 529.204,
      first_air_date: '2022-02-17',
      vote_average: 8.4,
      vote_count: 1444,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/ijRiyqrXUzrF77INhtzvSS6V6qG.jpg',
      id: 226637,
      name: 'High Potential',
      original_name: 'High Potential',
      overview:
        'Morgan is a single mom with an exceptional mind, whose unconventional knack for solving crimes leads to an unusual and unstoppable partnership with a by-the-book seasoned detective.',
      poster_path: '/ylTZ6bfmPrwUz01A0VpvluGFWsv.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 80],
      popularity: 574.644,
      first_air_date: '2024-09-17',
      vote_average: 8.5,
      vote_count: 85,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg',
      id: 823219,
      title: 'Flow',
      original_title: 'Straume',
      overview:
        'A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.',
      poster_path: '/imKSymKBK7o73sajciEmndJoVkR.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'lv',
      genre_ids: [16, 14, 12],
      popularity: 555.437,
      release_date: '2024-08-29',
      video: false,
      vote_average: 8.4,
      vote_count: 858,
    },
    {
      backdrop_path: '/fViElUGfdoZjtnVxvSpJX8TwxY6.jpg',
      id: 1013850,
      title: 'A Real Pain',
      original_title: 'A Real Pain',
      overview:
        "Mismatched cousins David and Benji reunite for a tour through Poland to honor their beloved grandmother. The adventure takes a turn when the pair's old tensions resurface against the backdrop of their family history.",
      poster_path: '/yaTFjMNh8D78dDHrglivOTv5YOx.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [35, 18],
      popularity: 294.22,
      release_date: '2024-11-01',
      video: false,
      vote_average: 6.8,
      vote_count: 251,
    },
    {
      backdrop_path: '/cSqUkhWH5seTIwtqUUAEBFjiLyh.jpg',
      id: 93405,
      name: 'Squid Game',
      original_name: '오징어 게임',
      overview:
        "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
      poster_path: '/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ko',
      genre_ids: [10759, 9648, 18],
      popularity: 3327.669,
      first_air_date: '2021-09-17',
      vote_average: 7.855,
      vote_count: 15167,
      origin_country: ['KR'],
    },
    {
      backdrop_path: '/z1buWt3MeqamyzVbKggLtlG1rZV.jpg',
      id: 259188,
      name: 'Drifting Away',
      original_name: '漂白',
      overview:
        'That winter, a horrific crime left veteran police captain Peng Zhaolin deeply shaken. A decade earlier, he had unknowingly crossed paths with the suspect, Deng Ligang, missing a crucial chance to stop the crime spree. Despite a relentless pursuit, the criminals vanished without a trace. Years later, a new clue emerges, prompting Peng Zhaolin and young officer Zhen Zhen to reopen the case and seek justice for the victims.',
      poster_path: '/bEcFBnDwUXXDizdaR5EiC0qRhS3.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'zh',
      genre_ids: [9648, 80],
      popularity: 26.383,
      first_air_date: '2025-01-17',
      vote_average: 6.3,
      vote_count: 3,
      origin_country: ['CN'],
    },
  ],
  total_pages: 500,
  total_results: 10000,
};

export const trendingMovie = {
  page: 1,
  results: [
    {
      backdrop_path: '/fYnEbgoNCxW9kL0IgOgtJb9JTBU.jpg',
      id: 426063,
      title: 'Nosferatu',
      original_title: 'Nosferatu',
      overview:
        'A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.',
      poster_path: '/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [27],
      popularity: 1359.239,
      release_date: '2024-12-25',
      video: false,
      vote_average: 6.658,
      vote_count: 1322,
    },
    {
      backdrop_path: '/zGLQmrmIB56kMZPnzqReIOBay1B.jpg',
      id: 507241,
      title: "The Killer's Game",
      original_title: "The Killer's Game",
      overview:
        "When top hitman Joe Flood is diagnosed with a terminal illness, he decides to take matters into his own hands – by taking a hit out on himself. But when the very hitmen he hired also target his ex-girlfriend, he must fend off an army of assassin colleagues and win back the love of his life before it's too late.",
      poster_path: '/4bKlTeOUr5AKrLky8mwWvlQqyVd.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 35, 80],
      popularity: 129.34,
      release_date: '2024-09-12',
      video: false,
      vote_average: 6.7,
      vote_count: 195,
    },
    {
      backdrop_path: '/b85bJfrTOSJ7M5Ox0yp4lxIxdG1.jpg',
      id: 939243,
      title: 'Sonic the Hedgehog 3',
      original_title: 'Sonic the Hedgehog 3',
      overview:
        'Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.',
      poster_path: '/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 878, 35, 10751],
      popularity: 6277.745,
      release_date: '2024-12-19',
      video: false,
      vote_average: 7.768,
      vote_count: 875,
    },
    {
      backdrop_path: '/uKb22E0nlzr914bA9KyA5CVCOlV.jpg',
      id: 402431,
      title: 'Wicked',
      original_title: 'Wicked',
      overview:
        "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
      poster_path: '/2E1x1qcHqGZcYuYi4PzVZjzg8IV.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 10749, 14],
      popularity: 1055.946,
      release_date: '2024-11-20',
      video: false,
      vote_average: 7,
      vote_count: 1435,
    },
    {
      backdrop_path: '/4cp40IyTpFfsT2IKpl0YlUkMBIR.jpg',
      id: 1064213,
      title: 'Anora',
      original_title: 'Anora',
      overview:
        'A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled.',
      poster_path: '/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [10749, 35, 18],
      popularity: 495.268,
      release_date: '2024-10-14',
      video: false,
      vote_average: 7.001,
      vote_count: 786,
    },
    {
      backdrop_path: '/hmZnqijPaaACjenDkrbWcCmcADI.jpg',
      id: 549509,
      title: 'The Brutalist',
      original_title: 'The Brutalist',
      overview:
        'Escaping post-war Europe, visionary architect László Tóth arrives in America to rebuild his life, his work, and his marriage to his wife Erzsébet after being forced apart during wartime by shifting borders and regimes. On his own in a strange new country, László settles in Pennsylvania, where the wealthy and prominent industrialist Harrison Lee Van Buren recognizes his talent for building. But power and legacy come at a heavy cost.',
      poster_path: '/vP7Yd6couiAaw9jgMd5cjMRj3hQ.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [18],
      popularity: 170.958,
      release_date: '2024-12-20',
      video: false,
      vote_average: 5.25,
      vote_count: 46,
    },
    {
      backdrop_path: '/u2eA9pqi1q3DvevT7RuDuJHxxBT.jpg',
      id: 974950,
      title: 'Emilia Pérez',
      original_title: 'Emilia Pérez',
      overview:
        'Rita, an underrated lawyer working for a large law firm more interested in getting criminals out of jail than bringing them to justice, is hired by the leader of a criminal organization.',
      poster_path: '/7seqaCaaXDNUHOx4DqwpoOH8pPa.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'fr',
      genre_ids: [18, 53],
      popularity: 229.26,
      release_date: '2024-08-21',
      video: false,
      vote_average: 7.7,
      vote_count: 866,
    },
    {
      backdrop_path: '/bFPqSvR2EmWQ9AlzWkC801XpoAZ.jpg',
      id: 933260,
      title: 'The Substance',
      original_title: 'The Substance',
      overview:
        'A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.',
      poster_path: '/lqoMzCcZYEFK729d6qzt349fB4o.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [27, 878],
      popularity: 850.494,
      release_date: '2024-09-07',
      video: false,
      vote_average: 7.1,
      vote_count: 3373,
    },
    {
      backdrop_path: '/66nlC5LDZmDUWONGkUZT2BrOszG.jpg',
      id: 974576,
      title: 'Conclave',
      original_title: 'Conclave',
      overview:
        'After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.',
      poster_path: '/m5x8D0bZ3eKqIVWZ5y7TnZ2oTVg.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [18],
      popularity: 269.122,
      release_date: '2024-10-25',
      video: false,
      vote_average: 7.132,
      vote_count: 916,
    },
    {
      backdrop_path: '/j9uruwRe9qM8RnP758dF7ISB8Bj.jpg',
      id: 1000837,
      title: "I'm Still Here",
      original_title: 'Ainda Estou Aqui',
      overview:
        'In the early 1970s, the military dictatorship in Brazil reaches its height. The Paiva family - Rubens, Eunice, and their five children - live in a beachside house in Rio, open to all their friends. One day, Rubens is taken for questioning and does not return.',
      poster_path: '/qNLMPY3KLrYgTX2QZ5iEwwOqyRz.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'pt',
      genre_ids: [18, 36],
      popularity: 77.493,
      release_date: '2024-09-19',
      video: false,
      vote_average: 8.5,
      vote_count: 158,
    },
    {
      backdrop_path: '/4WHRiFgbsAuSJ79fyr8pTXkj4G2.jpg',
      id: 661539,
      title: 'A Complete Unknown',
      original_title: 'A Complete Unknown',
      overview:
        'New York, early 1960s. Against the backdrop of a vibrant music scene and tumultuous cultural upheaval, an enigmatic 19-year-old from Minnesota arrives in the West Village with his guitar and revolutionary talent, destined to change the course of American music.',
      poster_path: '/662Mk69uIJvjA1zb5PYP4geje9H.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 10402, 36],
      popularity: 119.27,
      release_date: '2024-12-18',
      video: false,
      vote_average: 7.5,
      vote_count: 68,
    },
    {
      backdrop_path: '/xZm5YUNY3PlYD1Q4k7X8zd2V4AK.jpg',
      id: 993710,
      title: 'Back in Action',
      original_title: 'Back in Action',
      overview:
        'Fifteen years after vanishing from the CIA to start a family, elite spies Matt and Emily jump back into the world of espionage when their cover is blown.',
      poster_path: '/3L3l6LsiLGHkTG4RFB2aBA6BttB.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 35],
      popularity: 2277.176,
      release_date: '2025-01-15',
      video: false,
      vote_average: 6.7,
      vote_count: 419,
    },
    {
      backdrop_path: '/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg',
      id: 823219,
      title: 'Flow',
      original_title: 'Straume',
      overview:
        'A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.',
      poster_path: '/imKSymKBK7o73sajciEmndJoVkR.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'lv',
      genre_ids: [16, 14, 12],
      popularity: 555.437,
      release_date: '2024-08-29',
      video: false,
      vote_average: 8.4,
      vote_count: 858,
    },
    {
      backdrop_path: '/fViElUGfdoZjtnVxvSpJX8TwxY6.jpg',
      id: 1013850,
      title: 'A Real Pain',
      original_title: 'A Real Pain',
      overview:
        "Mismatched cousins David and Benji reunite for a tour through Poland to honor their beloved grandmother. The adventure takes a turn when the pair's old tensions resurface against the backdrop of their family history.",
      poster_path: '/yaTFjMNh8D78dDHrglivOTv5YOx.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [35, 18],
      popularity: 294.22,
      release_date: '2024-11-01',
      video: false,
      vote_average: 6.8,
      vote_count: 251,
    },
    {
      backdrop_path: '/rRBD8ORo9y34tYkAQJVbn4Ml6tu.jpg',
      id: 693134,
      title: 'Dune: Part Two',
      original_title: 'Dune: Part Two',
      overview:
        'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.',
      poster_path: '/6izwz7rsy95ARzTR3poZ8H6c5pp.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [878, 12],
      popularity: 279.616,
      release_date: '2024-02-27',
      video: false,
      vote_average: 8.151,
      vote_count: 6087,
    },
    {
      backdrop_path: '/1pmXyN3sKeYoUhu5VBZiDU4BX21.jpg',
      id: 1184918,
      title: 'The Wild Robot',
      original_title: 'The Wild Robot',
      overview:
        "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
      poster_path: '/9w0Vh9eizfBXrcomiaFWTIPdboo.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [16, 28, 878, 10751],
      popularity: 616.393,
      release_date: '2024-09-12',
      video: false,
      vote_average: 8.365,
      vote_count: 4065,
    },
    {
      backdrop_path: '/czoiFndZswfFcQxbHxWUGcSpajM.jpg',
      id: 1114894,
      title: 'Star Trek: Section 31',
      original_title: 'Star Trek: Section 31',
      overview:
        'Emperor Philippa Georgiou joins a secret division of Starfleet tasked with protecting the United Federation of Planets and faces the sins of her past.',
      poster_path: '/94IcxWKxu1l6AqjcXtlVI2jUb2t.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [878, 12],
      popularity: 39.337,
      release_date: '2025-01-15',
      video: false,
      vote_average: 5.5,
      vote_count: 2,
    },
    {
      backdrop_path: '/c0g0OprcXkRu61HlKM1fQv8qj8x.jpg',
      id: 1410082,
      title: 'Sniper: The Last Stand',
      original_title: 'Sniper: The Last Stand',
      overview:
        'To stop an arms dealer from unleashing a deadly superweapon, Ace sniper Brandon Beckett and Agent Zero are deployed to Costa Verde to lead a group of elite soldiers against an unrelenting militia. Taking an untested sniper under his wing, Beckett faces his newest challenge: giving orders instead of receiving them. With both time and ammo running low in a race to save humanity, the team must overcome all odds just to survive.',
      poster_path: '/TVvIyCsFCmLk9MRLbAZi4X8f32.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 53],
      popularity: 97.08,
      release_date: '2025-01-21',
      video: false,
      vote_average: 6.2,
      vote_count: 5,
    },
    {
      backdrop_path: '/v9Du2HC3hlknAvGlWhquRbeifwW.jpg',
      id: 539972,
      title: 'Kraven the Hunter',
      original_title: 'Kraven the Hunter',
      overview:
        "Kraven Kravinoff's complex relationship with his ruthless gangster father, Nikolai, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.",
      poster_path: '/i47IUSsN126K11JUzqQIOi1Mg1M.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 878, 12, 14, 53],
      popularity: 3611.48,
      release_date: '2024-12-11',
      video: false,
      vote_average: 6.6,
      vote_count: 754,
    },
    {
      backdrop_path: '/9V81UUI5MlRYgDCfK5E8iqi0eYM.jpg',
      id: 454626,
      title: 'Sonic the Hedgehog',
      original_title: 'Sonic the Hedgehog',
      overview:
        'Powered with incredible speed, Sonic The Hedgehog embraces his new home on Earth. That is, until Sonic sparks the attention of super-uncool evil genius Dr. Robotnik. Now it’s super-villain vs. super-sonic in an all-out race across the globe to stop Robotnik from using Sonic’s unique power for world domination.',
      poster_path: '/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 878, 35, 10751],
      popularity: 303.053,
      release_date: '2020-02-12',
      video: false,
      vote_average: 7.309,
      vote_count: 9691,
    },
  ],
  total_pages: 500,
  total_results: 10000,
};

export const trendingTV = {
  page: 1,
  results: [
    {
      backdrop_path: '/gklrevVndG98GHGDwfm8y8kxESo.jpg',
      id: 129552,
      name: 'The Night Agent',
      original_name: 'The Night Agent',
      overview:
        'Brought together by a midnight phone call, an FBI agent and a cybersecurity expert must unravel an ever-growing web of political conspiracies.',
      poster_path: '/4c5yUNcaff4W4aPrkXE6zr7papX.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 9648, 10759],
      popularity: 336.344,
      first_air_date: '2023-03-23',
      vote_average: 7.8,
      vote_count: 761,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/ehEvtUGaFPQ3EBZJCLJIv8a40vR.jpg',
      id: 246381,
      name: 'Prime Target',
      original_name: 'Prime Target',
      overview:
        'A brilliant math student is on the verge of a major breakthrough when a shadowy enemy tries to stop him. Fighting for answers—and his life—he teams up with a government agent to unravel a high-stakes conspiracy.',
      poster_path: '/bGYCimDXRL7cE3uETLZzMCFOdJo.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 80],
      popularity: 157.353,
      first_air_date: '2025-01-22',
      vote_average: 7.5,
      vote_count: 14,
      origin_country: ['GB'],
    },
    {
      backdrop_path: '/ixgFmf1X59PUZam2qbAfskx2gQr.jpg',
      id: 95396,
      name: 'Severance',
      original_name: 'Severance',
      overview:
        'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.',
      poster_path: '/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 9648, 10765],
      popularity: 529.204,
      first_air_date: '2022-02-17',
      vote_average: 8.4,
      vote_count: 1444,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/ijRiyqrXUzrF77INhtzvSS6V6qG.jpg',
      id: 226637,
      name: 'High Potential',
      original_name: 'High Potential',
      overview:
        'Morgan is a single mom with an exceptional mind, whose unconventional knack for solving crimes leads to an unusual and unstoppable partnership with a by-the-book seasoned detective.',
      poster_path: '/ylTZ6bfmPrwUz01A0VpvluGFWsv.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 80],
      popularity: 574.644,
      first_air_date: '2024-09-17',
      vote_average: 8.5,
      vote_count: 85,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/cSqUkhWH5seTIwtqUUAEBFjiLyh.jpg',
      id: 93405,
      name: 'Squid Game',
      original_name: '오징어 게임',
      overview:
        "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
      poster_path: '/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ko',
      genre_ids: [10759, 9648, 18],
      popularity: 3327.669,
      first_air_date: '2021-09-17',
      vote_average: 7.855,
      vote_count: 15167,
      origin_country: ['KR'],
    },
    {
      backdrop_path: '/z1buWt3MeqamyzVbKggLtlG1rZV.jpg',
      id: 259188,
      name: 'Drifting Away',
      original_name: '漂白',
      overview:
        'That winter, a horrific crime left veteran police captain Peng Zhaolin deeply shaken. A decade earlier, he had unknowingly crossed paths with the suspect, Deng Ligang, missing a crucial chance to stop the crime spree. Despite a relentless pursuit, the criminals vanished without a trace. Years later, a new clue emerges, prompting Peng Zhaolin and young officer Zhen Zhen to reopen the case and seek justice for the victims.',
      poster_path: '/bEcFBnDwUXXDizdaR5EiC0qRhS3.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'zh',
      genre_ids: [9648, 80],
      popularity: 26.383,
      first_air_date: '2025-01-17',
      vote_average: 6.3,
      vote_count: 3,
      origin_country: ['CN'],
    },
    {
      backdrop_path: '/9iwmsNVjbex9qa7FhqDUh92EjdQ.jpg',
      id: 225941,
      name: 'I Am Nobody',
      original_name: '异人之下',
      overview:
        'When a student unearths the truth behind his grandfather’s life, he must unveil his secret superpowers to an underworld eager for his emergence.',
      poster_path: '/aZT7iZwR4LE2kk7sXWslgpOP7oT.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'zh',
      genre_ids: [10759, 18, 10765],
      popularity: 1063.779,
      first_air_date: '2023-08-04',
      vote_average: 8.7,
      vote_count: 27,
      origin_country: ['CN'],
    },
    {
      backdrop_path: '/sgvq8FCeTF2Z4H86ebMgy2Iy2v1.jpg',
      id: 233347,
      name: 'Study Group',
      original_name: '스터디그룹',
      overview:
        'Nicknamed the "school for future criminals," Yuseong Technical High School isn\'t exactly the ideal place to study. A rarity among his peers, Ga-min is a student with just one goal: to get into university. At a school where it\'s every man for himself, he is rejected from countless study groups before he decides to form his own. Will he be able to defeat the odds and achieve his dreams?',
      poster_path: '/ptuejMBnO5YkW4WXyw5L2wY2kLi.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ko',
      genre_ids: [10759, 35],
      popularity: 86.8,
      first_air_date: '2025-01-23',
      vote_average: 0,
      vote_count: 0,
      origin_country: ['KR'],
    },
    {
      backdrop_path: '/n5FPNMJ0eRoiQrKGfUQQRAZeaxg.jpg',
      id: 125988,
      name: 'Silo',
      original_name: 'Silo',
      overview:
        'In a ruined and toxic future, thousands live in a giant silo deep underground. After its sheriff breaks a cardinal rule and residents die mysteriously, engineer Juliette starts to uncover shocking secrets and the truth about the silo.',
      poster_path: '/tlliQuCupf8fpTH7RAor3aKMGy.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [10765, 18],
      popularity: 759.306,
      first_air_date: '2023-05-04',
      vote_average: 8.172,
      vote_count: 1306,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/odqW5gNsXY1rGYGerGOy3wI4hJh.jpg',
      id: 274061,
      name: 'Whiskey on the Rocks',
      original_name: 'Whiskey on the Rocks',
      overview:
        'In the middle of the Cold War, a Soviet submarine runs aground outside Karlskrona and suddenly Sweden finds itself at the center of events. Prime Minister Thorbjörn Fälldin tries to resolve the conflict and avoid a world war between two nuclear powers while struggling with a wise foreign minister and a belligerent commander-in-chief.',
      poster_path: '/eFKnR4F6lqcoUDgNts87EsW3Sv9.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'sv',
      genre_ids: [18, 35, 10768],
      popularity: 21.309,
      first_air_date: '2024-12-25',
      vote_average: 6.7,
      vote_count: 7,
      origin_country: ['SE'],
    },
    {
      backdrop_path: '/4Mt7WHox67uJ1yErwTBFcV8KWgG.jpg',
      id: 37854,
      name: 'One Piece',
      original_name: 'ワンピース',
      overview:
        'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
      poster_path: '/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ja',
      genre_ids: [10759, 35, 16],
      popularity: 171.011,
      first_air_date: '1999-10-20',
      vote_average: 8.7,
      vote_count: 4766,
      origin_country: ['JP'],
    },
    {
      backdrop_path: '/1FxG2lmDYsCM1svJf7H79HNNwu2.jpg',
      id: 215866,
      name: 'American Primeval',
      original_name: 'American Primeval',
      overview:
        'A mother and son fleeing from their past form a found family while confronting a harsh landscape of freedom and cruelty in the American West.',
      poster_path: '/ff0s9OHGNSZL6cVteIb7LNvTnJD.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [37, 18, 10759],
      popularity: 414.2,
      first_air_date: '2025-01-09',
      vote_average: 7.652,
      vote_count: 135,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/lN13BPAEnc5iXmoxxBQHOZ1ScfZ.jpg',
      id: 86031,
      name: 'Dr. STONE',
      original_name: 'Dr.STONE',
      overview:
        "One fateful day, all of humanity was petrified by a blinding flash of light. After several millennia, high schooler Taiju awakens and finds himself lost in a world of statues. However, he's not alone! His science-loving friend Senku's been up and running for a few months and he's got a grand plan in mind, to kickstart civilization with the power of science!",
      poster_path: '/xbZQ3fDl0y5mt0ARwfeyrgQ4JTw.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ja',
      genre_ids: [10759, 16, 35, 10765],
      popularity: 47.908,
      first_air_date: '2019-07-05',
      vote_average: 8.5,
      vote_count: 1461,
      origin_country: ['JP'],
    },
    {
      backdrop_path: '/xnZD6FkvuPRnR8tKLx3j0JTBGfZ.jpg',
      id: 243083,
      name: 'Flourished Peony',
      original_name: '国色芳华',
      overview:
        "He Weifang, the daughter of a merchant, partners with the infamous Jiang Changyang to run a flower business, empowering women and challenging societal norms. As their bond deepens, He Weifang uncovers Jiang Changyang's true identity and is inspired to focus on ventures that benefit the greater good.",
      poster_path: '/4Kuw2vKrYaw6hBAL2IE3LNtvEzU.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'zh',
      genre_ids: [18],
      popularity: 548.011,
      first_air_date: '2025-01-07',
      vote_average: 8.3,
      vote_count: 6,
      origin_country: ['CN'],
    },
    {
      backdrop_path: '/sYXLeu5usz6yEz0k00FYvtEdodD.jpg',
      id: 94605,
      name: 'Arcane',
      original_name: 'Arcane',
      overview:
        'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
      poster_path: '/abf8tHznhSvl9BAElD2cQeRr7do.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [16, 10765, 18, 10759],
      popularity: 269.423,
      first_air_date: '2021-11-06',
      vote_average: 8.8,
      vote_count: 4814,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/mwffom1UZowlQ5bwaPU4LvhXJMP.jpg',
      id: 104416,
      name: 'Trident',
      original_name: '三叉戟',
      overview:
        'Cui Tiejun, Xu Guozhu, and Pan Jianghai, known as the Trident of the city police come together to fight crime.',
      poster_path: '/bKeeezPhIKaiN71bNgFDChHetpZ.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'zh',
      genre_ids: [80],
      popularity: 30.006,
      first_air_date: '2020-05-31',
      vote_average: 7.6,
      vote_count: 7,
      origin_country: ['CN'],
    },
    {
      backdrop_path: '/oskggc9don7i7TYSETRVHtjhwSi.jpg',
      id: 241485,
      name: 'Fight Night: The Million Dollar Heist',
      original_name: 'Fight Night: The Million Dollar Heist',
      overview:
        'The story of how on the night of Ali’s defeat of Jerry Quarry, which came after he was banned from boxing for refusing to enter the military draft, hundreds of guests at an after-party were robbed at gunpoint, becoming one of the largest armed robberies the country has ever seen.',
      poster_path: '/ucxvu9kRykTd23m1omktBJZG2Q1.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 80],
      popularity: 62.47,
      first_air_date: '2024-09-05',
      vote_average: 7.2,
      vote_count: 26,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/o0NsbcIvsllg6CJX0FBFY8wWbsn.jpg',
      id: 30984,
      name: 'Bleach',
      original_name: 'BLEACH',
      overview:
        'For as long as he can remember, Ichigo Kurosaki has been able to see ghosts. But when he meets Rukia, a Soul Reaper who battles evil spirits known as Hollows, he finds his life is changed forever. Now, with a newfound wealth of spiritual energy, Ichigo discovers his true calling: to protect the living and the dead from evil.',
      poster_path: '/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ja',
      genre_ids: [10759, 16, 10765],
      popularity: 207.767,
      first_air_date: '2004-10-05',
      vote_average: 8.383,
      vote_count: 1884,
      origin_country: ['JP'],
    },
    {
      backdrop_path: '/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg',
      id: 1429,
      name: 'Attack on Titan',
      original_name: '進撃の巨人',
      overview:
        'Many years ago, the last remnants of humanity were forced to retreat behind the towering walls of a fortified city to escape the massive, man-eating Titans that roamed the land outside their fortress. Only the heroic members of the Scouting Legion dared to stray beyond the safety of the walls – but even those brave warriors seldom returned alive. Those within the city clung to the illusion of a peaceful existence until the day that dream was shattered, and their slim chance at survival was reduced to one horrifying choice: kill – or be devoured!',
      poster_path: '/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ja',
      genre_ids: [16, 10765, 10759],
      popularity: 138.778,
      first_air_date: '2013-04-07',
      vote_average: 8.7,
      vote_count: 6531,
      origin_country: ['JP'],
    },
    {
      backdrop_path: '/8EFQphBeIqQY6K6Bp6dRQ2NygD9.jpg',
      id: 204610,
      name: 'Legend of the Undercover Chef',
      original_name: '鹊刀门传奇',
      overview:
        'This drama tells the story of Ximen Changhai, head of the Magpie Saber Sect, who is determined to eradicate the wokou pirates and joins a secret plan to do so. To prevent his plans from leaking out, Ximen Changhai brought his brother, Ximen Changzai, a cook, to the Magpie Saber Sect to become the acting sect head, and as affairs within the Sect changed, an amusing martial arts story started within the sect.',
      poster_path: '/t8zIqdV2hwqLwHh8WvOoV0uQFSv.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'zh',
      genre_ids: [35, 18],
      popularity: 200.955,
      first_air_date: '2023-08-18',
      vote_average: 8.4,
      vote_count: 8,
      origin_country: ['CN'],
    },
  ],
  total_pages: 500,
  total_results: 10000,
};

export const trendingPeople = {
  page: 1,
  results: [
    {
      id: 1729,
      name: 'James Horner',
      original_name: 'James Horner',
      media_type: 'person',
      adult: false,
      popularity: 8.501,
      gender: 2,
      known_for_department: 'Sound',
      profile_path: '/g2C3Fb4fHCU2gnqUcwTQCv5EZc4.jpg',
    },
    {
      id: 138781,
      name: 'Robert Eggers',
      original_name: 'Robert Eggers',
      media_type: 'person',
      adult: false,
      popularity: 60.639,
      gender: 2,
      known_for_department: 'Directing',
      profile_path: '/bZimaGzpcAvWlnX4UAStzkivWFx.jpg',
    },
    {
      id: 5602,
      name: 'David Lynch',
      original_name: 'David Lynch',
      media_type: 'person',
      adult: false,
      popularity: 83.321,
      gender: 2,
      known_for_department: 'Directing',
      profile_path: '/wwBzRDoIW6Ld64h6OkQ6ImCZKsR.jpg',
    },
    {
      id: 1027099,
      name: 'Fernando Méndez',
      original_name: 'Fernando Méndez',
      media_type: 'person',
      adult: false,
      popularity: 1.596,
      gender: 2,
      known_for_department: 'Directing',
      profile_path: null,
    },
    {
      id: 17496,
      name: 'Jacques Audiard',
      original_name: 'Jacques Audiard',
      media_type: 'person',
      adult: false,
      popularity: 10.245,
      gender: 2,
      known_for_department: 'Directing',
      profile_path: '/dJ2XCySH5NKZTEEapYK3RaBtL61.jpg',
    },
    {
      id: 12835,
      name: 'Vin Diesel',
      original_name: 'Vin Diesel',
      media_type: 'person',
      adult: false,
      popularity: 91.685,
      gender: 2,
      known_for_department: 'Acting',
      profile_path: '/nZdVry7lnUkE24PnXakok9okvL4.jpg',
    },
    {
      id: 3416,
      name: 'Demi Moore',
      original_name: 'Demi Moore',
      media_type: 'person',
      adult: false,
      popularity: 64.233,
      gender: 1,
      known_for_department: 'Acting',
      profile_path: '/gPgZSodybMFBodw7nKRTALONIr2.jpg',
    },
    {
      id: 1384838,
      name: 'Doris May',
      original_name: 'Doris May',
      media_type: 'person',
      adult: false,
      popularity: 1.114,
      gender: 1,
      known_for_department: 'Acting',
      profile_path: '/h7po7TuRDSaPue0Wylcss1ugToO.jpg',
    },
    {
      id: 366,
      name: 'James Mangold',
      original_name: 'James Mangold',
      media_type: 'person',
      adult: false,
      popularity: 13.919,
      gender: 2,
      known_for_department: 'Directing',
      profile_path: '/pk0GDjn99crNwR4qgCCEokDYd71.jpg',
    },
    {
      id: 87335,
      name: 'Fernanda Torres',
      original_name: 'Fernanda Torres',
      media_type: 'person',
      adult: false,
      popularity: 13.455,
      gender: 1,
      known_for_department: 'Acting',
      profile_path: '/dkxdADNwbM7ZLQK5YBNeKBqVJNM.jpg',
    },
    {
      id: 60898,
      name: 'Sebastian Stan',
      original_name: 'Sebastian Stan',
      media_type: 'person',
      adult: false,
      popularity: 56.863,
      gender: 2,
      known_for_department: 'Acting',
      profile_path: '/nKZgixTbHFXpkzzIpMFdLX98GYh.jpg',
    },
    {
      id: 4430,
      name: 'Sharon Stone',
      original_name: 'Sharon Stone',
      media_type: 'person',
      adult: false,
      popularity: 38.432,
      gender: 1,
      known_for_department: 'Acting',
      profile_path: '/eg8DKQGLJrIA1Yjee0y7K5K6QWq.jpg',
    },
    {
      id: 1622390,
      name: 'Lee Chae-dam',
      original_name: 'Lee Chae-dam',
      media_type: 'person',
      adult: false,
      popularity: 22.846,
      gender: 1,
      known_for_department: 'Acting',
      profile_path: '/7wMyr6F3yzvbSpu2XMxSW3vObED.jpg',
    },
    {
      id: 74752,
      name: 'Nikolaj Arcel',
      original_name: 'Nikolaj Arcel',
      media_type: 'person',
      adult: false,
      popularity: 3.217,
      gender: 2,
      known_for_department: 'Directing',
      profile_path: '/79JljyWnfjqE87UyTo7xgFQa5fy.jpg',
    },
    {
      id: 4857772,
      name: 'Kim Soo-ji',
      original_name: 'Kim Soo-ji',
      media_type: 'person',
      adult: false,
      popularity: 44.714,
      gender: 1,
      known_for_department: 'Acting',
      profile_path: '/51Nbexh5jSbUi6QX5Hw26te31Xm.jpg',
    },
    {
      id: 1590797,
      name: 'Sadie Sink',
      original_name: 'Sadie Sink',
      media_type: 'person',
      adult: false,
      popularity: 55.482,
      gender: 1,
      known_for_department: 'Acting',
      profile_path: '/vo5x9GRs2vT47LNb1HZvKUEsk8C.jpg',
    },
    {
      id: 2472212,
      name: 'Sae Bom',
      original_name: 'Sae Bom',
      media_type: 'person',
      adult: false,
      popularity: 12.568,
      gender: 1,
      known_for_department: 'Acting',
      profile_path: '/mM43mwxU8YAbRFJPFEwoFYV0CQO.jpg',
    },
    {
      id: 118415,
      name: 'Sean Baker',
      original_name: 'Sean Baker',
      media_type: 'person',
      adult: false,
      popularity: 21.169,
      gender: 2,
      known_for_department: 'Directing',
      profile_path: '/wKfNgfRvPhLHMrwuweSwLOmhRzT.jpg',
    },
    {
      id: 25837,
      name: 'Elisha Cuthbert',
      original_name: 'Elisha Cuthbert',
      media_type: 'person',
      adult: false,
      popularity: 90.52,
      gender: 1,
      known_for_department: 'Acting',
      profile_path: '/lsNwsJjGZqgjVUI1mhtcDCuwES3.jpg',
    },
    {
      id: 2484644,
      name: 'Kim Hee-jeong',
      original_name: 'Kim Hee-jeong',
      media_type: 'person',
      adult: false,
      popularity: 50.461,
      gender: 1,
      known_for_department: 'Acting',
      profile_path: '/3GxSLhLzUa26ZffrJPOjsIBU7WW.jpg',
    },
  ],
  total_pages: 172,
  total_results: 3440,
};

export const searchResult = {
  page: 1,
  results: [
    {
      id: 2128617,
      name: 'Iron',
      original_name: 'Iron',
      media_type: 'person',
      adult: false,
      popularity: 0.001,
      gender: 2,
      known_for_department: 'Acting',
      profile_path: '/28iTo42JqjBXzq3aLtKfNwWzO4K.jpg',
      known_for: [
        {
          backdrop_path: '/8jsvRzKyB1s7YU9e40prhBJyIez.jpg',
          id: 68884,
          name: 'Show Me The Money',
          original_name: 'Show Me The Money',
          overview:
            'From newcomers to rappers already loved by many fans, all gather to compete against each other in order to pick the best Hip hop entertainer. The one that receives the most votes from the audience takes it all.',
          poster_path: '/zyzD9DGJWyA3VDMrS6ZzmW61SAd.jpg',
          media_type: 'tv',
          adult: false,
          original_language: 'ko',
          genre_ids: [10764],
          popularity: 29.82,
          first_air_date: '2012-06-22',
          vote_average: 7.7,
          vote_count: 3,
          origin_country: ['KR'],
        },
      ],
    },
    {
      backdrop_path: '/4diQCWNckcvrjGhgSYdCBOpu1BP.jpg',
      id: 242875,
      name: 'Iron Reign',
      original_name: 'Mano de hierro',
      overview:
        "Joaquín Manchado rules his drug empire from Barcelona's seaport with an iron fist — until a new shipment sends business and family spiraling.",
      poster_path: '/fc1oDqW2Gi1vzzloMwcRFXgtjdM.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'es',
      genre_ids: [80, 18],
      popularity: 24.42,
      first_air_date: '2024-03-15',
      vote_average: 6.7,
      vote_count: 41,
      origin_country: ['ES'],
    },
    {
      backdrop_path: '/rDDn1U7m9WcSGUCgod9nllRGFMH.jpg',
      id: 36248,
      name: 'Linebarrels of Iron',
      original_name: '鉄のラインバレル',
      overview:
        'Centers around Kouichi Hayase, a fourteen-year-old boy living a mediocre life, until an accident turns him into the pilot of a gigantic robot called "Linebarrel" and leads him to encounter a mysterious girl.',
      poster_path: '/ieHjmuA24mG0InX2WZH7uQ9TfEy.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ja',
      genre_ids: [18, 16, 35, 18],
      popularity: 69.277,
      first_air_date: '2008-10-03',
      vote_average: 4.667,
      vote_count: 3,
      origin_country: ['JP'],
    },
    {
      backdrop_path: '/y6tNFGDgWN0wklx8HWi0gvQ2Gn4.jpg',
      id: 84104,
      name: 'Iron Island',
      original_name: 'Ilha de Ferro',
      overview:
        'On an offshore oil rig, "Iron Island" showcases the duality of people who have their lives torn apart: wherever they are, they feel incomplete. In this scenario, Dante, the oil rig\'s production coordinator, is an irascible man who sees his life collapsing between the turmoil in the high seas and family dilemmas on solid ground.',
      poster_path: '/jN03YxeJ4eylVbUuavYUdL84N4T.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'pt',
      genre_ids: [18],
      popularity: 6.041,
      first_air_date: '2018-11-15',
      vote_average: 6.9,
      vote_count: 11,
      origin_country: ['BR'],
    },
    {
      backdrop_path: null,
      id: 1158328,
      title: 'IRON',
      original_title: 'IRON',
      overview: '',
      poster_path: null,
      media_type: 'movie',
      adult: false,
      original_language: 'ja',
      genre_ids: [18],
      popularity: 0.665,
      release_date: '2006-06-03',
      video: false,
      vote_average: 0.5,
      vote_count: 1,
    },
    {
      backdrop_path: '/rGpgCQbdWvAThLKASFlFWWPdj3r.jpg',
      id: 65945,
      name: 'Kabaneri of the Iron Fortress',
      original_name: '甲鉄城のカバネリ',
      overview:
        'In the midst of an industrial revolution, the people of Hinomoto fight hordes of undead creatures, known as Kabane, using powerful armored trains.',
      poster_path: '/a9lY3DCLU3DWvUshho6hAX2hKKh.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ja',
      genre_ids: [16, 18, 10759, 10765],
      popularity: 47.997,
      first_air_date: '2016-04-08',
      vote_average: 6.9,
      vote_count: 147,
      origin_country: ['JP'],
    },
    {
      id: 16940,
      name: 'Jeremy Irons',
      original_name: 'Jeremy Irons',
      media_type: 'person',
      adult: false,
      popularity: 45.427,
      gender: 2,
      known_for_department: 'Acting',
      profile_path: '/w8Ct1q02Ht3sWdOSqfp3B85TzT.jpg',
      known_for: [
        {
          backdrop_path: '/wXsQvli6tWqja51pYxXNG1LFIGV.jpg',
          id: 8587,
          title: 'The Lion King',
          original_title: 'The Lion King',
          overview:
            'Young lion prince Simba, eager to one day become king of the Pride Lands, grows up under the watchful eye of his father Mufasa; all the while his villainous uncle Scar conspires to take the throne for himself. Amid betrayal and tragedy, Simba must confront his past and find his rightful place in the Circle of Life.',
          poster_path: '/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg',
          media_type: 'movie',
          adult: false,
          original_language: 'en',
          genre_ids: [10751, 16, 18],
          popularity: 149.678,
          release_date: '1994-06-24',
          video: false,
          vote_average: 8.3,
          vote_count: 18480,
        },
        {
          backdrop_path: '/e29oMyfzzlWbhRlCBrzmZhlsw2m.jpg',
          id: 121856,
          title: "Assassin's Creed",
          original_title: "Assassin's Creed",
          overview:
            'Through a technology that unlocks the generic memories of his ancestor in 15th century Spain, Callum Lynch discovers he is a descendant of an ancient line of Assassins and amasses lethal skills to take on the oppressive Templar Order.',
          poster_path: '/nhiShTvoga8fyGX8468hLj6pCtW.jpg',
          media_type: 'movie',
          adult: false,
          original_language: 'en',
          genre_ids: [28, 12, 878],
          popularity: 24.411,
          release_date: '2016-12-21',
          video: false,
          vote_average: 5.4,
          vote_count: 7738,
        },
        {
          backdrop_path: '/5fX1oSGuYdKgwWmUTAN5MNSQGzr.jpg',
          id: 209112,
          title: 'Batman v Superman: Dawn of Justice',
          original_title: 'Batman v Superman: Dawn of Justice',
          overview:
            'Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.',
          poster_path: '/5UsK3grJvtQrtzEgqNlDljJW96w.jpg',
          media_type: 'movie',
          adult: false,
          original_language: 'en',
          genre_ids: [28, 12, 14],
          popularity: 76.121,
          release_date: '2016-03-23',
          video: false,
          vote_average: 6,
          vote_count: 18060,
        },
      ],
    },
    {
      backdrop_path: null,
      id: 800180,
      title: 'Ferrum',
      original_title: 'Iron',
      overview:
        'Unconventional portrayal of mining in the Swedish Lapland ore fields, a powerful image and sound symphony that can be experienced both as a documentary and symbolic work.',
      poster_path: '/2EGrlDiOp6Nv2vopEwuLdZl7I6E.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'sv',
      genre_ids: [99, 10402],
      popularity: 0.314,
      release_date: '1963-01-01',
      video: false,
      vote_average: 9,
      vote_count: 2,
    },
    {
      backdrop_path: '/auyjsGDtFGKJRjMWLxIStdBmajJ.jpg',
      id: 18867,
      name: 'The Iron Empress',
      original_name: '천추태후',
      overview:
        "Empress Cheonchu is a 2009 South Korean period television series based on the titular character, an actual historical figure and her lifelong struggle to protect the country her ancestors built. The granddaughter of Goryeo Dynasty founder Taejo Wanggeon, the empress ruled as the regent for her son Mokjong, the dynasty's seventh ruler. Determined to realize her ambitious goals for the kingdom of Goryeo, she dons armor, battles against foreign invaders, and tramples her lover, her son and brother in her rise to power.",
      poster_path: '/bseGN199uoDDtUJIk2N4Wbc4gHl.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ko',
      genre_ids: [18],
      popularity: 107.681,
      first_air_date: '2009-01-03',
      vote_average: 4.8,
      vote_count: 4,
      origin_country: ['KR'],
    },
    {
      backdrop_path: '/3Sp1HHLAnHXpi6cNxGMFLhHCFJ4.jpg',
      id: 73458,
      name: 'Iron Lady Cha',
      original_name: '불굴의 차여사',
      overview:
        'A drama about three generations of a family; parents in their 50s who sacrifice their lives to their children and their parents.',
      poster_path: '/tfn6sLHCV5XfrjD5cl7qMSojp6m.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ko',
      genre_ids: [10751, 18],
      popularity: 235.527,
      first_air_date: '2015-01-05',
      vote_average: 2,
      vote_count: 1,
      origin_country: ['KR'],
    },
    {
      backdrop_path: '/uKTkiw3w3LfdzgiPOvu0C19Voi3.jpg',
      id: 1047041,
      title: 'Detective Conan: Black Iron Submarine',
      original_title: '名探偵コナン 黒鉄の魚影（サブマリン）',
      overview:
        'Many engineers from around the world gather at the Interpol marine facility "Pacific Buoy" on Hachijo-jima, in the sea south of central Tokyo Prefecture coast, to witness the launch of a new system that connects all law enforcement camera systems around the world and enables facial recognition worldwide. Conan, along with his friends Kogoro, Ran, Agasa, Haibara, and the Detective Boys, also heads to the island with an invitation from Sonoko to see the whales. He receives a message from Subaru, who says that a Europol agent has been murdered in Germany by Gin. Perturbed, Conan sneaks onto the police ship led by Kuroda, which is bringing them to the island to protect the completion work, and tours the new facility, just in time for the Black Organization to kidnap a female engineer, seeking a piece of important data in her USB drive. A terrifying howl of screws is heard from the ocean as an unknown person approaches Haibara.',
      poster_path: '/ksQ8uNgoWsVH6a0oPB6zx08pOwU.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'ja',
      genre_ids: [16, 28, 80, 9648],
      popularity: 63.369,
      release_date: '2023-04-14',
      video: false,
      vote_average: 6.9,
      vote_count: 106,
    },
    {
      backdrop_path: '/Ak8Jk2L3mnoFjb6DN4EF6367AJJ.jpg',
      id: 45058,
      name: 'Shippuu! Iron Leaguer',
      original_name: '疾風! アイアンリーガー',
      overview:
        'Shippū! Iron Leaguer is an anime television series produced by Sunrise. Directed by Tetsurō Amino and featuring mecha designs by Kunio Okawara, it premiered on TV Tokyo on April 6, 1993 and ended its run on March 29, 1994, spanning a total of 52 episodes.',
      poster_path: '/k12pmq0lxJywXR474LSsXhtiV4r.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ja',
      genre_ids: [16],
      popularity: 144.294,
      first_air_date: '1993-04-06',
      vote_average: 6,
      vote_count: 4,
      origin_country: ['JP'],
    },
    {
      backdrop_path: '/4cwCkzFo6A2NtsjvM5SCsW0EHUs.jpg',
      id: 77017,
      name: 'Iron Ladies',
      original_name: '姊的時代',
      overview:
        'To the outside world, everything in their lives is going well for them. But three professional women in their 30s try to find their own personal happiness outside of their successful careers.',
      poster_path: '/iWPk7y7e4rb0yHZLYN9keUbNs9h.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'zh',
      genre_ids: [18],
      popularity: 22.012,
      first_air_date: '2018-01-12',
      vote_average: 8,
      vote_count: 1,
      origin_country: ['TW'],
    },
    {
      backdrop_path: '/uizVGHUX0FLyp4KhnRZMFfQORZR.jpg',
      id: 157627,
      name: 'The Iron Four',
      original_name: '我和我的鋼四壁',
      overview: '',
      poster_path: '/1dXcybsHzdOnwHZlhw20iRtrz0p.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'zh',
      genre_ids: [18],
      popularity: 25.834,
      first_air_date: '2022-02-28',
      vote_average: 0,
      vote_count: 0,
      origin_country: ['TW'],
    },
    {
      backdrop_path: '/fkgvxWEJHJGHIVhdixBjpclOHMz.jpg',
      id: 64375,
      name: 'Mobile Suit Gundam: Iron-Blooded Orphans',
      original_name: '機動戦士ガンダム 鉄血のオルフェンズ',
      overview:
        'When Mikazuki Augus, a young member of a private security company known as the CGS, accepts a mission to protect a young woman seeking to liberate the Martian city of Chryse from Earth’s rule, he sets off a chain of events that threatens to send the galaxy back to war.',
      poster_path: '/4CuZBnOBafYCI7WKfOkHUSElZCw.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ja',
      genre_ids: [16, 10768, 10759, 10765],
      popularity: 47.574,
      first_air_date: '2015-10-04',
      vote_average: 7.5,
      vote_count: 50,
      origin_country: ['JP'],
    },
    {
      backdrop_path: '/nb4nsmvWjGD4J3Dm5g2KsW9JiWm.jpg',
      id: 109195,
      name: 'The Lady of Iron',
      original_name: '男盜女差',
      overview: '',
      poster_path: '/c6D7HSS2CeCRcJcZQrJAPlqUwe7.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'cn',
      genre_ids: [],
      popularity: 2.953,
      first_air_date: '1991-09-09',
      vote_average: 0,
      vote_count: 0,
      origin_country: ['HK'],
    },
    {
      id: 11086,
      name: 'Michael Ironside',
      original_name: 'Michael Ironside',
      media_type: 'person',
      adult: false,
      popularity: 23.231,
      gender: 2,
      known_for_department: 'Acting',
      profile_path: '/mzHmxtKcMJjDqWxKd67mKQJFW1B.jpg',
      known_for: [
        {
          backdrop_path: '/jILeJ60zPpIjjJHGSmIeY4eO30t.jpg',
          id: 744,
          title: 'Top Gun',
          original_title: 'Top Gun',
          overview:
            "For Lieutenant Pete 'Maverick' Mitchell and his friend and co-pilot Nick 'Goose' Bradshaw, being accepted into an elite training school for fighter pilots is a dream come true. But a tragedy, as well as personal demons, will threaten Pete's dreams of becoming an ace pilot.",
          poster_path: '/xUuHj3CgmZQ9P2cMaqQs4J0d4Zc.jpg',
          media_type: 'movie',
          adult: false,
          original_language: 'en',
          genre_ids: [28, 18],
          popularity: 69.526,
          release_date: '1986-05-16',
          video: false,
          vote_average: 7.057,
          vote_count: 8699,
        },
        {
          backdrop_path: '/u2J7HxrT9QtzIy37S5q3RdrzxXD.jpg',
          id: 615457,
          title: 'Nobody',
          original_title: 'Nobody',
          overview:
            'Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a "nobody." When two thieves break into his home one night, Hutch\'s unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.',
          poster_path: '/kvjrWTQrJKG1BfsZQTzOjYlutkj.jpg',
          media_type: 'movie',
          adult: false,
          original_language: 'en',
          genre_ids: [28, 53],
          popularity: 62.878,
          release_date: '2021-03-18',
          video: false,
          vote_average: 7.938,
          vote_count: 7177,
        },
        {
          backdrop_path: '/e9zfOyNd3YaViIGadiqWg9x8pAq.jpg',
          id: 861,
          title: 'Total Recall',
          original_title: 'Total Recall',
          overview:
            "Construction worker Douglas Quaid's obsession with the planet Mars leads him to visit Recall, a company that manufactures memories. When his memory implant goes wrong, Doug can no longer be sure what is and isn't reality.",
          poster_path: '/wVbeL6fkbTKSmNfalj4VoAUUqJv.jpg',
          media_type: 'movie',
          adult: false,
          original_language: 'en',
          genre_ids: [28, 12, 878],
          popularity: 36.672,
          release_date: '1990-06-01',
          video: false,
          vote_average: 7.308,
          vote_count: 5850,
        },
      ],
    },
    {
      backdrop_path: '/tOwVV3cJzhlYYL8OMeLbXejffDf.jpg',
      id: 83107,
      name: "Thirty Years' War: The Age Of Iron",
      original_name:
        'Die Eiserne Zeit - Lieben und Töten im Dreißigjährigen Krieg',
      overview:
        'This documentary drama series tells the story of the Thirty Years War from the perspective of the people who experienced it: like the soldier Peter Hagendorf, the "Winter Queen" Elisabeth Stuart, the famous artist Peter Paul Rubens and the "Grey Eminence" Father Joseph. This visual memory of the 17th century forms the \'archive footage\' in the series. Combined with vivid drama and contributions from international experts, the series builds a bridge between "now" and "then" enabling viewers to experience what it was like to live through the Thirty Years\' War.',
      poster_path: '/q0IR4IXPxhFlCgLDGOyXYstmMRm.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'de',
      genre_ids: [99],
      popularity: 8.815,
      first_air_date: '2018-10-13',
      vote_average: 5.7,
      vote_count: 3,
      origin_country: ['FR', 'DE', 'PT'],
    },
    {
      backdrop_path: '/mUqZ9etYy3UFaswZ5KnKKraH8mT.jpg',
      id: 109615,
      name: 'Iron Grandma',
      original_name: 'アイアングランマ',
      overview: '',
      poster_path: '/mjyw4upfc1QPOlg4G9pX8Thageg.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ja',
      genre_ids: [18, 35],
      popularity: 5.201,
      first_air_date: '2015-01-10',
      vote_average: 0,
      vote_count: 0,
      origin_country: ['JP'],
    },
    {
      backdrop_path: '/7lYBvjfgrguOUgnS9NrpysHtaCq.jpg',
      id: 4582,
      name: 'Ironside',
      original_name: 'Ironside',
      overview:
        "When an assassin's bullet confines him to a wheelchair for life ending his career as Chief of Detectives, Robert T. Ironside becomes a consultant to the police department. Detective Sergeant Ed Brown and policewoman Eve Whitfield join with him to crack varied and fascinating cases. Ex-con Mark Sanger is employed by the chief as home help but eventually becomes a fully fledged member of the team also. Officer Whitfield leaves after 4 years service, and is replaced by Officer Fran Belding.",
      poster_path: '/Fu9Sv0pQ0s89uWwwXcaG0kiNW7.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [80, 18, 9648],
      popularity: 105.282,
      first_air_date: '1967-03-28',
      vote_average: 6.903,
      vote_count: 62,
      origin_country: ['US'],
    },
  ],
  total_pages: 58,
  total_results: 1149,
};
